name: WEB E2E Test
on: workflow_dispatch

jobs:
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      # clone do projeto do github para a máquina
      - name: Checkout
        uses: actions/checkout@v4

      # Conferir a versão instalada
      - name: Node version
        run: node --version
      
      # Instalando dependências
      - name: Instalando dependências
        run: npm install
      
      # Rodando os testes
      - name: Rodando os testes
        run: npx cypress run

      # Relatórios
      - uses: actions/upload-artifact@v4
        if: ${{ !cancelled()}}
        with: 
          name: relatorios
        path: |
          cypress/reports/
          cypress/video/
          cypress/screenshots/
        
